
const DATA=[

    {
        Image : "https://cdn.icon-icons.com/icons2/1674/PNG/512/person_110935.png",
        title:'My Account',
               
    },
    {
        Image : "https://cdn.icon-icons.com/icons2/1674/PNG/512/person_110935.png",
        title:'Category',
               
    },
    {
        Image : "https://cdn.icon-icons.com/icons2/1674/PNG/512/person_110935.png",
        title:'Payment Method',
               
    },
    {
        Image : "https://cdn.icon-icons.com/icons2/1674/PNG/512/person_110935.png",
        title:'Settings',
               
    },
    {
        Image : "https://cdn.icon-icons.com/icons2/1674/PNG/512/person_110935.png",
        title:'Help & Support',
               
    },
    
    ]
    
    export default DATA;